<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicule;
use Carbon\Carbon;

class VehiculeSeeder extends Seeder
{
    public function run(): void
    {
        $vehicules = [
            [
                'brand' => 'Toyota',
                'model' => 'Hilux',
                'matricule' => '12345-A-45',
                'num_chassis' => 'JTMHV05J504123456',
                'circulation_date' => '2020-01-15',
                'total_km' => 125000,
                'total_hours' => null,
                'horses' => 150,
                'number_of_tires' => 4,
                'tire_size' => '265/70R16',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.5,
                'max_fuel_consumption_100km' => 11.5,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => 2,
            ],
            [
                'brand' => 'Mercedes',
                'model' => 'Sprinter',
                'matricule' => '67890-B-50',
                'num_chassis' => 'WDB9066331N123456',
                'circulation_date' => '2019-03-20',
                'total_km' => 185000,
                'total_hours' => null,
                'horses' => 163,
                'number_of_tires' => 4,
                'tire_size' => '225/70R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 9.0,
                'max_fuel_consumption_100km' => 12.0,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addMonths(2)->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'permis_id' => 2,
            ],
            [
                'brand' => 'Renault',
                'model' => 'Master',
                'matricule' => '11111-C-55',
                'num_chassis' => 'VF1MA0000A1234567',
                'circulation_date' => '2021-06-10',
                'total_km' => 95000,
                'total_hours' => null,
                'horses' => 125,
                'number_of_tires' => 4,
                'tire_size' => '215/75R16',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.0,
                'max_fuel_consumption_100km' => 10.5,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'permis_id' => 2,
            ],
            [
                'brand' => 'Iveco',
                'model' => 'Daily',
                'matricule' => '22222-D-60',
                'num_chassis' => 'ZCFC45E0000123456',
                'circulation_date' => '2018-09-05',
                'total_km' => 220000,
                'total_hours' => 3500,
                'horses' => 146,
                'number_of_tires' => 4,
                'tire_size' => '195/75R16',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 9.5,
                'max_fuel_consumption_100km' => 13.0,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->subDays(15)->format('Y-m-d'), // Expired
                'technicalvisite_expiration' => Carbon::now()->addDays(10)->format('Y-m-d'),
                'permis_id' => 2,
            ],
            [
                'brand' => 'Peugeot',
                'model' => 'Partner',
                'matricule' => '33333-E-65',
                'num_chassis' => 'VF3A5HHR0CS123456',
                'circulation_date' => '2022-02-14',
                'total_km' => 45000,
                'total_hours' => null,
                'horses' => 100,
                'number_of_tires' => 4,
                'tire_size' => '185/65R15',
                'fuel_type' => 'Essence',
                'min_fuel_consumption_100km' => 7.5,
                'max_fuel_consumption_100km' => 9.5,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(12)->format('Y-m-d'),
                'permis_id' => 1,
            ],
            [
                'brand' => 'Ford',
                'model' => 'Transit',
                'matricule' => '44444-F-70',
                'num_chassis' => 'NM0AE8F77E1123456',
                'circulation_date' => '2020-11-30',
                'total_km' => 140000,
                'total_hours' => null,
                'horses' => 130,
                'number_of_tires' => 4,
                'tire_size' => '215/70R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.0,
                'max_fuel_consumption_100km' => 11.0,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addDays(20)->format('Y-m-d'), // Expiring soon
                'technicalvisite_expiration' => Carbon::now()->addDays(25)->format('Y-m-d'), // Expiring soon
                'permis_id' => 2,
            ],
            [
                'brand' => 'Volvo',
                'model' => 'FH16',
                'matricule' => '55555-G-75',
                'num_chassis' => 'YV2M4C123A1234567',
                'circulation_date' => '2017-05-18',
                'total_km' => 350000,
                'total_hours' => 8500,
                'horses' => 500,
                'number_of_tires' => 10,
                'tire_size' => '315/70R22.5',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 28.0,
                'max_fuel_consumption_100km' => 35.0,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'permis_id' => 3,
            ],
            [
                'brand' => 'Citroen',
                'model' => 'Berlingo',
                'matricule' => '66666-H-80',
                'num_chassis' => 'VF7B9HHR0CS123456',
                'circulation_date' => '2021-08-22',
                'total_km' => 78000,
                'total_hours' => null,
                'horses' => 110,
                'number_of_tires' => 4,
                'tire_size' => '185/65R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 6.5,
                'max_fuel_consumption_100km' => 8.5,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(10)->format('Y-m-d'),
                'permis_id' => 1,
            ],
        ];

        foreach ($vehicules as $vehicule) {
            Vehicule::create($vehicule);
        }
    }
}
