<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicule;
use Carbon\Carbon;

class VehiculeSeeder extends Seeder
{
    public function run(): void
    {
        // Get permis category B (most common for vehicles)
        $permisB = \App\Models\CategoriePermi::where('label', 'B')->first();
        $permisC = \App\Models\CategoriePermi::where('label', 'C')->first();
        $permisD = \App\Models\CategoriePermi::where('label', 'D')->first();
        
        // Default permis if not found
        $defaultPermis = $permisB ? $permisB->id : 2;

        $vehicules = [
            // 01-05: Dacia vehicles from 2019
            [
                'brand' => 'Dacia',
                'model' => 'Dokker',
                'matricule' => 'J223122',
                'num_chassis' => 'UFD0F5F20KJ223122',
                'circulation_date' => '2019-01-15',
                'total_km' => 45000,
                'total_hours' => null,
                'horses' => 90,
                'number_of_tires' => 4,
                'tire_size' => '185/65 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 4.5,
                'max_fuel_consumption_100km' => 6.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            [
                'brand' => 'Dacia',
                'model' => 'Dokker',
                'matricule' => 'J223123',
                'num_chassis' => 'UFD0F5F20KJ223123',
                'circulation_date' => '2019-02-20',
                'total_km' => 42000,
                'total_hours' => null,
                'horses' => 90,
                'number_of_tires' => 4,
                'tire_size' => '185/65 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 4.5,
                'max_fuel_consumption_100km' => 6.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            [
                'brand' => 'Dacia',
                'model' => 'Dokker',
                'matricule' => 'J223124',
                'num_chassis' => 'UFD0F5F20KJ223124',
                'circulation_date' => '2019-03-10',
                'total_km' => 48000,
                'total_hours' => null,
                'horses' => 90,
                'number_of_tires' => 4,
                'tire_size' => '185/65 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 4.5,
                'max_fuel_consumption_100km' => 6.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            [
                'brand' => 'Dacia',
                'model' => 'Logan',
                'matricule' => 'J223125',
                'num_chassis' => 'UFD0F5F20KJ223125',
                'circulation_date' => '2019-04-05',
                'total_km' => 50000,
                'total_hours' => null,
                'horses' => 75,
                'number_of_tires' => 4,
                'tire_size' => '175/65 R14',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 4.0,
                'max_fuel_consumption_100km' => 5.5,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            [
                'brand' => 'Dacia',
                'model' => 'Logan',
                'matricule' => 'J223126',
                'num_chassis' => 'UFD0F5F20KJ223126',
                'circulation_date' => '2019-05-12',
                'total_km' => 46000,
                'total_hours' => null,
                'horses' => 75,
                'number_of_tires' => 4,
                'tire_size' => '175/65 R14',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 4.0,
                'max_fuel_consumption_100km' => 5.5,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 06: Dacia Logan 2010
            [
                'brand' => 'Dacia',
                'model' => 'Logan',
                'matricule' => 'J175927',
                'num_chassis' => 'UFD0F5F20KJ175927',
                'circulation_date' => '2010-06-15',
                'total_km' => 180000,
                'total_hours' => null,
                'horses' => 75,
                'number_of_tires' => 4,
                'tire_size' => '175/65 R14',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 4.5,
                'max_fuel_consumption_100km' => 6.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 07: Pick-up Mitsubishi 2010
            [
                'brand' => 'Mitsubishi',
                'model' => 'L200',
                'matricule' => 'J175961',
                'num_chassis' => 'MMBJNKB10CJ175961',
                'circulation_date' => '2010-07-20',
                'total_km' => 200000,
                'total_hours' => null,
                'horses' => 150,
                'number_of_tires' => 4,
                'tire_size' => '265/70 R16',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.0,
                'max_fuel_consumption_100km' => 11.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 08: Hyundai H 1 2019
            [
                'brand' => 'Hyundai',
                'model' => 'H1',
                'matricule' => 'J223171',
                'num_chassis' => 'KMHGH81J1KU223171',
                'circulation_date' => '2019-08-10',
                'total_km' => 35000,
                'total_hours' => null,
                'horses' => 120,
                'number_of_tires' => 4,
                'tire_size' => '215/70 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 7.5,
                'max_fuel_consumption_100km' => 10.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 09: Fiat Doblo 2017
            [
                'brand' => 'Fiat',
                'model' => 'Doblo',
                'matricule' => 'J211170',
                'num_chassis' => 'ZFA2230000HJ211170',
                'circulation_date' => '2017-09-15',
                'total_km' => 120000,
                'total_hours' => null,
                'horses' => 95,
                'number_of_tires' => 4,
                'tire_size' => '185/65 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 5.0,
                'max_fuel_consumption_100km' => 7.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 10: Renault Kangoo 2010
            [
                'brand' => 'Renault',
                'model' => 'Kangoo',
                'matricule' => 'J175989',
                'num_chassis' => 'VF1K90B00AJ175989',
                'circulation_date' => '2010-10-20',
                'total_km' => 190000,
                'total_hours' => null,
                'horses' => 90,
                'number_of_tires' => 4,
                'tire_size' => '185/65 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 5.5,
                'max_fuel_consumption_100km' => 7.5,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 11: Ford Transit 2017
            [
                'brand' => 'Ford',
                'model' => 'Transit',
                'matricule' => 'J211354',
                'num_chassis' => 'NM0AE8F77HJ211354',
                'circulation_date' => '2017-11-05',
                'total_km' => 130000,
                'total_hours' => null,
                'horses' => 130,
                'number_of_tires' => 4,
                'tire_size' => '215/70 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.0,
                'max_fuel_consumption_100km' => 11.0,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 12: Fiat Ducato 2014
            [
                'brand' => 'Fiat',
                'model' => 'Ducato',
                'matricule' => 'J194508',
                'num_chassis' => 'ZFA2500000HJ194508',
                'circulation_date' => '2014-12-10',
                'total_km' => 250000,
                'total_hours' => null,
                'horses' => 130,
                'number_of_tires' => 4,
                'tire_size' => '215/70 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.5,
                'max_fuel_consumption_100km' => 11.5,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 13: Renault Laguna 2009
            [
                'brand' => 'Renault',
                'model' => 'Laguna',
                'matricule' => 'J170439',
                'num_chassis' => 'VF1BZ0F00AJ170439',
                'circulation_date' => '2009-01-15',
                'total_km' => 220000,
                'total_hours' => null,
                'horses' => 110,
                'number_of_tires' => 4,
                'tire_size' => '205/55 R16',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 5.5,
                'max_fuel_consumption_100km' => 7.5,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
            // 14: Renault Nacelle 1998
            [
                'brand' => 'Renault',
                'model' => 'Nacelle',
                'matricule' => 'J129225',
                'num_chassis' => 'VF1K90B00AJ129225',
                'circulation_date' => '1998-02-20',
                'total_km' => 350000,
                'total_hours' => 8500,
                'horses' => 120,
                'number_of_tires' => 4,
                'tire_size' => '215/70 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 9.0,
                'max_fuel_consumption_100km' => 12.0,
                'min_fuel_consumption_hour' => 3.5,
                'max_fuel_consumption_hour' => 5.0,
                'airbag' => false,
                'abs' => false,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $permisC ? $permisC->id : $defaultPermis,
            ],
            // 15: Tracteur Landini 1998
            [
                'brand' => 'Landini',
                'model' => 'Tracteur',
                'matricule' => 'J126485',
                'num_chassis' => 'LAN126485000000',
                'circulation_date' => '1998-03-10',
                'total_km' => 50000,
                'total_hours' => 12000,
                'horses' => 75,
                'number_of_tires' => 4,
                'tire_size' => '16.9-30',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => null,
                'max_fuel_consumption_100km' => null,
                'min_fuel_consumption_hour' => 8.0,
                'max_fuel_consumption_hour' => 12.0,
                'airbag' => false,
                'abs' => false,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $permisD ? $permisD->id : $defaultPermis,
            ],
            // 16: Camion Mozimank 2009
            [
                'brand' => 'Mozimank',
                'model' => 'Camion',
                'matricule' => 'J166754',
                'num_chassis' => 'MOZ166754000000',
                'circulation_date' => '2009-04-15',
                'total_km' => 280000,
                'total_hours' => 6000,
                'horses' => 250,
                'number_of_tires' => 6,
                'tire_size' => '295/80 R22.5',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 20.0,
                'max_fuel_consumption_100km' => 28.0,
                'min_fuel_consumption_hour' => 10.0,
                'max_fuel_consumption_hour' => 15.0,
                'airbag' => false,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $permisC ? $permisC->id : $defaultPermis,
            ],
            // 17: جرافة Palazzani 2002
            [
                'brand' => 'Palazzani',
                'model' => 'Excavator',
                'matricule' => 'J137116',
                'num_chassis' => 'PAL137116000000',
                'circulation_date' => '2002-05-20',
                'total_km' => 15000,
                'total_hours' => 15000,
                'horses' => 100,
                'number_of_tires' => 4,
                'tire_size' => '23.5-25',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => null,
                'max_fuel_consumption_100km' => null,
                'min_fuel_consumption_hour' => 12.0,
                'max_fuel_consumption_hour' => 18.0,
                'airbag' => false,
                'abs' => false,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $permisD ? $permisD->id : $defaultPermis,
            ],
            // 18: Fiat Ducato 2010
            [
                'brand' => 'Fiat',
                'model' => 'Ducato',
                'matricule' => 'J177698',
                'num_chassis' => 'ZFA2500000HJ177698',
                'circulation_date' => '2010-06-25',
                'total_km' => 240000,
                'total_hours' => null,
                'horses' => 130,
                'number_of_tires' => 4,
                'tire_size' => '215/70 R15',
                'fuel_type' => 'Diesel',
                'min_fuel_consumption_100km' => 8.5,
                'max_fuel_consumption_100km' => 11.5,
                'min_fuel_consumption_hour' => null,
                'max_fuel_consumption_hour' => null,
                'airbag' => true,
                'abs' => true,
                'inssurance_expiration' => Carbon::now()->addYear()->format('Y-m-d'),
                'technicalvisite_expiration' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'permis_id' => $defaultPermis,
            ],
        ];

        foreach ($vehicules as $vehicule) {
            Vehicule::create($vehicule);
        }
    }
}
